/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as MerchantLoginRouteImport } from './routes/merchant.login'
import { Route as DeliveryLoginRouteImport } from './routes/delivery.login'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedDashboardNewStoreRouteImport } from './routes/_authenticated/dashboard/new-store'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStoresRouteImport } from './routes/_authenticated/admin/stores'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminMerchantsRouteImport } from './routes/_authenticated/admin/merchants'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin/delivery'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin/catalog'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin/broadcast'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin/ads'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoresRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant/login',
  path: '/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryLoginRoute = DeliveryLoginRouteImport.update({
  id: '/delivery/login',
  path: '/delivery/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardNewStoreRoute =
  AuthenticatedDashboardNewStoreRouteImport.update({
    id: '/new-store',
    path: '/new-store',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStoresRoute =
  AuthenticatedAdminStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMerchantsRoute =
  AuthenticatedAdminMerchantsRouteImport.update({
    id: '/merchants',
    path: '/merchants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/products/$id': typeof ProductsIdRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/new-store': typeof AuthenticatedDashboardNewStoreRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/products/$id': typeof ProductsIdRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/new-store': typeof AuthenticatedDashboardNewStoreRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/merchant': typeof AuthenticatedMerchantRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/products/$id': typeof ProductsIdRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/new-store': typeof AuthenticatedDashboardNewStoreRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/stores'
    | '/admin'
    | '/cart'
    | '/dashboard'
    | '/delivery'
    | '/favorites'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/categories/$slug'
    | '/delivery/login'
    | '/merchant/login'
    | '/products/$id'
    | '/stores/$slug'
    | '/admin/ads'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/dashboard/new-store'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/stores'
    | '/cart'
    | '/dashboard'
    | '/delivery'
    | '/favorites'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/categories/$slug'
    | '/delivery/login'
    | '/merchant/login'
    | '/products/$id'
    | '/stores/$slug'
    | '/admin/ads'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/dashboard/new-store'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/stores'
    | '/_authenticated/admin'
    | '/_authenticated/cart'
    | '/_authenticated/dashboard'
    | '/_authenticated/delivery'
    | '/_authenticated/favorites'
    | '/_authenticated/merchant'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/categories/$slug'
    | '/delivery/login'
    | '/merchant/login'
    | '/products/$id'
    | '/stores/$slug'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/merchants'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stores'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/new-store'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  StoresRoute: typeof StoresRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DeliveryLoginRoute: typeof DeliveryLoginRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof StoresRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/login': {
      id: '/merchant/login'
      path: '/merchant/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/login': {
      id: '/delivery/login'
      path: '/delivery/login'
      fullPath: '/delivery/login'
      preLoaderRoute: typeof DeliveryLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/new-store': {
      id: '/_authenticated/dashboard/new-store'
      path: '/new-store'
      fullPath: '/dashboard/new-store'
      preLoaderRoute: typeof AuthenticatedDashboardNewStoreRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stores': {
      id: '/_authenticated/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/merchants': {
      id: '/_authenticated/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AuthenticatedAdminMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminMerchantsRoute: typeof AuthenticatedAdminMerchantsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoresRoute: typeof AuthenticatedAdminStoresRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
  AuthenticatedAdminMerchantsRoute: AuthenticatedAdminMerchantsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoresRoute: AuthenticatedAdminStoresRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardNewStoreRoute: typeof AuthenticatedDashboardNewStoreRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardNewStoreRoute: AuthenticatedDashboardNewStoreRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedMerchantRoute: AuthenticatedMerchantRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface StoresRouteChildren {
  StoresSlugRoute: typeof StoresSlugRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresSlugRoute: StoresSlugRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  StoresRoute: StoresRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DeliveryLoginRoute: DeliveryLoginRoute,
  MerchantLoginRoute: MerchantLoginRoute,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
